config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: "pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :shakes do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :shake
   validates :quantity, presence: true
  validates :ingredient, uniqueness: { scope: :shake }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :quantity
end

app/models/shake.rb
class Shake < ApplicationRecord
  has_many :ingredient
  has_many :doses, dependent: :destroy
  validates :name, presence: true
  belongs_to :user
  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :shakes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  # def index
  #   if params[:query].present?
  #     sql_query = " \
  #       shakes.name @@ :query \
  #       OR ingredients.name @@ :query \
  #     "
  #     @doses = Dose.joins(:shake).where(sql_query, query: "%#{params[:query]}%")
  #   else
  #     @doses = Dose.all
  #   end
  # end

  def new
    @shake = Shake.find(params[:shake_id])
    @dose = Dose.new
    authorize @dose
  end

  def create
    @shake = Shake.find(params[:shake_id])
    @dose = Dose.new(dose_strong_params)
    @dose.shake = @shake
    if @dose.save
      redirect_to shake_path(@shake)
    else
      render :new
    end
    authorize @dose
  end

  def destroy
    authorize @dose
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to shake_path(@dose.shake)
  end

  def dose_strong_params
    params.require(:dose).permit(:quantity, :ingredient_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/shakes_controller.rb
class ShakesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @shakes = policy_scope(Shake)
   if params[:query].present?
      sql_query = " \
        shakes.name @@ :query \
      "
      @shakes = Shake.where(sql_query, query: "%#{params[:query]}%")
    else
      @shakes = Shake.all
      authorize @shakes
    end
  end

  def show
    @shake = Shake.find(params[:id])
    authorize @shake
  end

  def new
    @shake = Shake.new
    authorize @shake
  end

  def create
    @shake = Shake.new(shake_strong_params)
    authorize @shake
    if @shake.save
      redirect_to shake_path(@shake)
    else
      render :new
    end
  end

  def destroy
    authorize @shake
    @shake = Shake.find(params[:id])
    @shake.destroy
    redirect_to root_path
  end

  def shake_strong_params
    params.require(:shake).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/shakes_helper.rb
module ShakesHelper
end

app/views/doses/new.html.erb
<div class="container">
  <h2>Add dose</h2>
  <%= simple_form_for [@shake, @dose] do |f| %>
  <%= f.input :quantity %>
  <%= f.association :ingredient%>
  <%= f.submit "Add to your recipe", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>My Protein Shake</title>
   <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'shared/navbar' %>
  <%= yield %>

  <%= javascript_include_tag "application" %>
  <%= javascript_pack_tag "application" %>
</body>
</html>

app/views/pages/home.html.erb
<div class="banner-home">
  <div class="search">
    <li>
      <%= form_tag shakes_path, method: :get do %>
      <%= text_field_tag :query,
      params[:query],
      class: "form-control",
        placeholder: "Find your shake recipe"
        %>
    </li>
    <li>
      <button type="submit">
        <i class="fas fa-search"></i>
      </button>
    </li>
    <% end %>
  </div>
</div>

app/views/shakes/index.html.erb
<div class="banner">

  <div class="container">

    <h1>Daily protein shake recipe</h1>
    <p>A shake a day, keep the doctor away.</p>
  </div>
</div>

  <div class="container">
    <div class="card-category">
      <% @shakes.each do |shake| %>
      <div class="card">
        <h3><%= link_to shake.name, shake_path(shake), class: 'card-text' %></h3>
        <% if policy(shake).destroy? %>
        <%= link_to shake_path(shake), method: :delete, data: { confirm: "Are you sure?" } do %>
        <i class="fa fa-trash destroy_dose"></i>
        <% end %>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>


<div class="footer">
  <ul>
    <li><a href="#">
      <i class="fab fa-linkedin-in"></i></a>
    </li>
    <li><a href="#">
      <i class="fab fa-twitter"></i></a>
    </li>
    <li><a href="#">
      <i class="fab fa-github"></i></a>
    </li>
  </ul>
  <p>Sharing is loving! Share your shake</p>
</div>

app/views/shakes/new.html.erb
<div class="container">
  <%= simple_form_for @shake do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit "create cocktail", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/shakes/show.html.erb
<div class="banner-show" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
url('<%= cl_image_path @shake.photo.url, height: 800, width: 1080, crop: :fill %>')">
</div>

<div class="container">
  <div class="add">
    <li><h2><%= @shake.name %></h2></li>
    <li><h2><%= link_to "add to your shake", new_shake_dose_path(@shake), class: "btn btn-primary" %></h2></li>
  </div>
  <div class="dose">
    <% @shake.doses.each do |dose| %>
    <p><%= dose.ingredient.name %> <%= dose.quantity %>
      <% if policy(dose).destroy? %>
      <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
      <i class="fa fa-trash destroy_dose"></i>
      <% end %>
      <% end %>
    </p>
      <% end %>
  </div>
</div>

<div class="footer">
  <ul>
    <li><a href="#">
      <i class="fab fa-linkedin-in"></i></a></li>
    <li><a href="#">
      <i class="fab fa-twitter"></i></a></li>
    <li><a href="#">
      <i class="fab fa-github"></i></a></li>
  </ul>
  <p>Sharing is loving! Share your shake</p>
</div>

app/views/shared/_navbar.html.erb
  <% if current_page?("/") %>
  <% else %>
  <div class="navbar">
    <li><%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://cdn2.iconfinder.com/data/icons/bubble-milk-tea/500/bubble-tea-drink_17-512.png" %>
      <% end %>
    </li>
    <li>
      <% if current_user %>
      <% if policy(Shake).new? %>
      <%= link_to "New recipe", new_shake_path %>
      <% end %>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
      <% else %>
      <%= link_to "Sign in", new_user_session_path  %>
      <% end %>
    </li>
  </div>
  <% end %>